src/Entity/Recipe.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecipeRepository")
 */
class Recipe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Cost;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $difficulty;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $People;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCost(): ?string
    {
        return $this->Cost;
    }

    public function setCost(string $Cost): self
    {
        $this->Cost = $Cost;

        return $this;
    }

    public function getDifficulty(): ?string
    {
        return $this->difficulty;
    }

    public function setDifficulty(string $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getTime(): ?string
    {
        return $this->time;
    }

    public function setTime(string $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getPeople(): ?string
    {
        return $this->People;
    }

    public function setPeople(string $People): self
    {
        $this->People = $People;

        return $this;
    }
}

src/Controller/recetteController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class recetteController extends AbstractController

{
    /**
     * @Route("/", name="accueil")
     */

    public function accueil()
    {
        

        return $this->render("accueil.html.twig");
    }

    /**
     * @Route("/index1", name="recipes")
     */
    public function index1()
    {
        $rec = $this->getDoctrine()->getRepository(Recipe::class);
        $recipes = $rec->findAll();
        return $this->render("index1.html.twig", [
            "controller_name" => "recetteController", "recipe" => $recipes,
        ]);
    }

    /**
     * @Route("/index2", name="index2")
     */
    public function index2()
    {
        

        return $this->render("index2.html.twig");
    }
    /**
     * @Route("/index3", name="index3")
     */
    public function index3()
    {
        

        return $this->render("index3.html.twig");
    }
}
?>

templates/accueil.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet"/>
    <link rel="icon" type="image/png" href="img/icon.png"/>
    <title>Cuisine Française</title>
</head>
<body>
 <div class="header_accueil">
        <div class="logo_accueil">
<h1>La cuisine Française</h1>
        </div>
    </div>
   <div class="bar_accueil">
        <p class="bar_text"> <a href="http://127.0.0.1:8000/index1">Les entrées</a> <a href="#">Les plats</a> <a href="#">Les desserts</a> </p>
    </div>
  
</body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/index1.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet"/>
     <link rel="icon" type="image/png" href="img/icon.png"/>
    <title>Les Entrées</title>
</head>

<body>
<div class="header">
        <div class="logo">

        </div>
    </div>
    <div class="bar">
        <p class="bar_text_index">Les Entrées</p>
    </div>

    <div class="recette">
        <div class="type">
            <div class="img_type_pate"></div>
            <div class="manger">
                <p>Paté en croute</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Cout: {% for recipes in recipe %}
                                {{ recipes.cost }}
                                    </p>
                    <p>Nb de Personnes:
                                {{ recipes.people }}
                                    </p>
                </div>
                <div class="prepa">
                    <p>Difficulté :
                                {{ recipes.difficulty }}
                            </p>
                    <p>Temps de préparation: 
                                {{ recipes.time }}
                                    {% endfor %}</p>
                </div>
            </div>
        </div>
     
</body>
</html>

templates/index2.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet"/>
     <link rel="icon" type="image/png" href="img/icon.png"/>
    <title>Les plats</title>
</head>
<body>
 <div class="header">
        <div class="logo">

        </div>
    </div>
    <div class="bar">
        <p class="bar_text_index">Les Plats</p>
    </div>
     <div class="recette">
        <div class="type">
            <div class="img_type_bourg"></div>
            <div class="manger">
                <p>Bourguignon</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Ingrédients :</p>
                </div>
                <div class="prepa">
                    <p>Préparations :</p>
                </div>
            </div>
        </div>
        <div class="type">
            <div class="img_type_cass"></div>
            <div class="manger">
                <p>Cassoulet</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Ingrédients :</p>
                </div>
                <div class="prepa">
                    <p>Préparations :</p>
                </div>
            </div>

        </div>
        <div class="type">
            <div class="img_type_coq"></div>
            <div class="manger">
                <p>Coq au vin</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Ingrédients :</p>
                </div>
                <div class="prepa">
                    <p>Préparations :</p>
                </div>
            </div>
        </div>

        <div class="type">
            <div class="img_type_blan"></div>
            <div class="manger">
                <p>Blanquette de veau</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Ingrédients :</p>
                </div>
                <div class="prepa">
                    <p>Préparations :</p>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

templates/index3.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet"/>
    <link rel="icon" type="image/png" href="img/icon.png"/>
    <title>Les desserts</title>
</head>
<body>
 <div class="header">
        <div class="logo">

        </div>
    </div>
     <div class="bar">
        <p class="bar_text_index">Les Desserts</p>
    </div>
     <div class="recette">
        <div class="type">
            <div class="img_type_tarte"></div>
            <div class="manger">
                <p>Tarte au sucre</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Ingrédients :</p>
                </div>
                <div class="prepa">
                    <p>Préparations :</p>
                </div>
            </div>
        </div>
        <div class="type">
            <div class="img_type_eclair"></div>
            <div class="manger">
                <p>Eclair au chocolat</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Ingrédients :</p>
                </div>
                <div class="prepa">
                    <p>Préparations :</p>
                </div>
            </div>

        </div>
        <div class="type">
            <div class="img_type_pain"></div>
            <div class="manger">
                <p>Pain perdu</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Ingrédients :</p>
                </div>
                <div class="prepa">
                    <p>Préparations :</p>
                </div>
            </div>
        </div>

        <div class="type">
            <div class="img_type_ile"></div>
            <div class="manger">
                <p>Ile flottante</p>
            </div>
            <div class="block_recette">
                <div class="ingre">
                    <p>Ingrédients :</p>
                </div>
                <div class="prepa">
                    <p>Préparations :</p>
                </div>
            </div>
        </div>

    </div>
    
</body>
</html>